# Generated by Django 5.2.7 on 2025-12-03 15:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectNegotiation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('agreed', 'Agreed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proposed_deadline', models.DateField(blank=True, null=True)),
                ('agreed_deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_projectnegotiation',
                'ordering': ['-created_at'],
            },
        ),
    ]
