# Generated by Django 5.2.7 on 2025-12-03 15:54

import apps.projects.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.CharField(default=apps.projects.models.generate_project_id, max_length=20, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('stage', models.CharField(choices=[('proposal', 'Proposal'), ('data_analysis', 'Data Analysis'), ('literature_review', 'Literature Review'), ('methodology', 'Methodology'), ('full_project', 'Full Project')], max_length=20)),
                ('support_type', models.CharField(choices=[('sample_size', 'Sample Size Calculation'), ('analysis_plan', 'Analysis Plan'), ('statistical_analysis', 'Statistical Analysis'), ('data_cleaning', 'Data Cleaning'), ('methodology_review', 'Methodology Review'), ('report_writing', 'Report Writing'), ('reproducible_notebook', 'Reproducible Notebook'), ('other', 'Other')], max_length=50)),
                ('research_area', models.CharField(max_length=255)),
                ('sample_size', models.IntegerField(blank=True, null=True)),
                ('preferred_methods', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('qa', 'QA Review'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('disputed', 'Disputed')], default='submitted', max_length=20)),
                ('confirms_lawful_use', models.BooleanField(default=False)),
                ('confirms_data_rights', models.BooleanField(default=False)),
                ('irb_approval_provided', models.BooleanField(default=False)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('released_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to='users.pseudonymoususer')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='users.pseudonymoususer')),
            ],
            options={
                'db_table': 'core_project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('due_date', models.DateField()),
                ('delivery_instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed - Ready for Review'), ('approved', 'Approved - Payment Ready'), ('rejected', 'Rejected - Needs Revision')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('unfunded', 'Unfunded'), ('processing', 'Processing Payment'), ('funded', 'Funded - Payment Received'), ('released', 'Released to Admin'), ('refunded', 'Refunded to Client'), ('failed', 'Payment Failed')], default='unfunded', max_length=20)),
                ('gateway_used', models.CharField(blank=True, choices=[('paypal', 'PayPal'), ('paystack', 'PayStack')], max_length=20, null=True)),
                ('paypal_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_auth_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paystack_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('paystack_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'db_table': 'core_milestone',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deliverable_type', models.CharField(choices=[('report', 'PDF Report'), ('notebook', 'Reproducible Notebook'), ('code', 'Code Bundle'), ('data_log', 'Data Processing Log'), ('sow', 'Statement of Work'), ('qa_report', 'QA Report')], max_length=50)),
                ('file', models.FileField(upload_to='deliverables/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.pseudonymoususer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='projects.project')),
            ],
            options={
                'db_table': 'core_deliverable',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='project_files/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.pseudonymoususer')),
            ],
            options={
                'db_table': 'core_projectfile',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_progress/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='project_progress/thumbnails/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='projects.project')),
            ],
            options={
                'db_table': 'core_projectprogress',
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_id'], name='core_projec_project_96ab66_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client', 'status'], name='core_projec_client__f4eed2_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='core_projec_status_2020cc_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['project', 'status'], name='core_milest_project_f15b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['payment_status'], name='core_milest_payment_e8bb5c_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['due_date'], name='core_milest_due_dat_198701_idx'),
        ),
    ]
