# Generated by Django 5.2.7 on 2025-12-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional document with additional project details', null=True, upload_to='project_attachments/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='project',
            name='attachment_filename',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('under_100', 'Under $100'), ('100_250', '$100 - $250'), ('250_500', '$250 - $500'), ('500_1000', '$500 - $1,000'), ('1000_2500', '$1,000 - $2,500'), ('2500_5000', '$2,500 - $5,000'), ('5000_10000', '$5,000 - $10,000'), ('10000_plus', '$10,000+'), ('discuss', "Let's Discuss")], help_text='Expected budget range for the project', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline_range',
            field=models.CharField(blank=True, choices=[('1_5_days', '1 - 5 Days'), ('5_10_days', '5 - 10 Days'), ('10_20_days', '10 - 20 Days'), ('20_30_days', '20 - 30 Days'), ('1_2_months', '1 - 2 Months'), ('2_3_months', '2 - 3 Months'), ('3_plus_months', '3+ Months'), ('flexible', 'Flexible / No Rush')], help_text='Expected timeline for project completion', max_length=20, null=True),
        ),
    ]
