# Generated by Django 5.2.7 on 2026-07-15 20:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_is_active_project_sub_admin_fee_and_more'),
        ('users', '0002_pseudonymoususer_is_sub_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('message', 'Message'), ('progress', 'Progress'), ('file', 'File'), ('payment', 'Payment'), ('milestone', 'Milestone'), ('review', 'Review'), ('deadline', 'Deadline'), ('completion', 'Completion'), ('system', 'System')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_section', models.CharField(blank=True, choices=[('project-overview', 'Project Overview'), ('project-communication', 'Communication'), ('project-progress', 'Progress'), ('project-deliverables', 'Deliverables'), ('project-payments', 'Payments'), ('project-milestones', 'Milestones'), ('project-final-deliverables', 'Final Deliverables')], default='project-overview', max_length=50)),
                ('related_object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_activities', to='users.pseudonymoususer')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_project_activities', to='users.pseudonymoususer')),
            ],
            options={
                'db_table': 'core_projectactivity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'recipient', '-created_at'], name='core_projec_project_50bc7e_idx'), models.Index(fields=['project', 'recipient', 'is_read'], name='core_projec_project_fd2dd6_idx'), models.Index(fields=['project', 'activity_type'], name='core_projec_project_572513_idx')],
            },
        ),
    ]
