# Generated by Django 5.2.7 on 2025-12-03 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonepayment',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='projects.milestone'),
        ),
        migrations.AddIndex(
            model_name='milestonepayment',
            index=models.Index(fields=['milestone', 'gateway'], name='core_milest_milesto_817b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='milestonepayment',
            index=models.Index(fields=['gateway_reference'], name='core_milest_gateway_957a56_idx'),
        ),
    ]
