# Generated by Django 5.2.7 on 2026-04-30 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pseudonymoususer',
            name='is_sub_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pseudonymoususer',
            name='parent_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_users', to='users.pseudonymoususer'),
        ),
    ]
